package com.illumined.app.ui
// Original preparation aids; parish review required. Not official ritual text.
internal object SacramentGuideTemplates {
 val all = listOf(
RiteGuideTemplate("sacrament-baptism", mapOf("title" to "Baptism",
"meaning" to "Baptism joins you to Christ and welcomes you into his Church. It forgives sin and begins a new life of grace. This is God’s gift, not a reward for knowing every answer.",
"meaningHeading" to "New Life in Christ",
"context" to "Bring your questions to your instructor and godparent. Reflect on your desire to follow Jesus and on changes you are making in daily life. An unbaptized person prepares for Baptism, not sacramental confession before Baptism. If you were previously baptized, ask the parish to review your baptismal record; a valid Baptism is not repeated.",
"contextHeading" to "Preparing for Baptism",
"studentActions" to "You will approach with your godparent, renounce sin, and profess the Church’s faith. Listen to each question and respond as rehearsed. The minister baptizes with water and the invocation of the Father, Son, and Holy Spirit.",
"studentActionsHeading" to "What You Will Do",
"ministerActions" to "Your parish will explain how water will be used and the signs of the white garment and lighted candle. In adult initiation, Confirmation and first Holy Communion normally follow in the same celebration. Follow the celebrant’s guidance.",
"ministerActionsHeading" to "Water, Prayer, and the Church’s Welcome",
"preparation" to "Confirm the rehearsal, arrival time, clothing, accessibility needs, and your godparent’s place. Ask whether a towel or change of clothing is needed. Afterward, continue meeting with your parish, attending Mass, praying, and exploring the meaning of your new life.",
"preparationHeading" to "Practical Preparation and Life After Baptism"), mapOf("title" to "Bautismo",
"meaning" to "El Bautismo te une a Cristo y te recibe en su Iglesia. Perdona el pecado e inicia una vida nueva de gracia. Es un don de Dios, no un premio por saber todas las respuestas.",
"meaningHeading" to "Vida nueva en Cristo",
"context" to "Comparte tus preguntas con tu instructor y tu padrino o madrina. Reflexiona sobre tu deseo de seguir a Jesús y los cambios que estás haciendo en tu vida. Una persona no bautizada se prepara para el Bautismo, no para la confesión sacramental antes del Bautismo. Si ya fuiste bautizado, pide a la parroquia que revise tu certificado; un Bautismo válido no se repite.",
"contextHeading" to "Prepararte para el Bautismo",
"studentActions" to "Te acercarás con tu padrino o madrina, renunciarás al pecado y profesarás la fe de la Iglesia. Escucha cada pregunta y responde según lo ensayado. El ministro bautiza con agua e invoca al Padre, al Hijo y al Espíritu Santo.",
"studentActionsHeading" to "Tu participación",
"ministerActions" to "La parroquia explicará cómo se utilizará el agua y los signos de la vestidura blanca y la vela encendida. En la iniciación de adultos, normalmente siguen la Confirmación y la primera Comunión en la misma celebración. Sigue las indicaciones del celebrante.",
"ministerActionsHeading" to "El agua, la oración y la acogida de la Iglesia",
"preparation" to "Confirma el ensayo, la hora de llegada, la ropa, las necesidades de accesibilidad y el lugar de tu padrino o madrina. Pregunta si necesitas una toalla o ropa de cambio. Después, sigue reuniéndote con la parroquia, asistiendo a Misa, orando y profundizando en tu vida nueva.",
"preparationHeading" to "Preparación práctica y vida después del Bautismo")),
RiteGuideTemplate("sacrament-confirmation", mapOf("title" to "Confirmation",
"meaning" to "Confirmation strengthens baptismal grace and equips you to bear witness to Jesus in the Church and in everyday life. Ask the Holy Spirit for courage, wisdom, and a generous heart.",
"meaningHeading" to "Receiving the Gift of the Holy Spirit",
"context" to "Review the baptismal promises and pray about how you will live them. A baptized person should prepare to receive Confirmation in a state of grace, with sacramental confession as appropriate. Someone receiving Baptism immediately beforehand does not need confession before that Baptism. Discuss your situation privately with the priest.",
"contextHeading" to "Preparing Your Heart and Renewing Your Faith",
"studentActions" to "Confirm your sponsor’s role and where to stand. Your parish will rehearse the presentation of your name, any renewal of baptismal promises, and your responses. You do not need to memorize a speech; listen and respond prayerfully.",
"studentActionsHeading" to "Your Participation and Your Sponsor",
"ministerActions" to "The bishop or an authorized priest prays for the gift of the Holy Spirit and anoints your forehead with sacred chrism. Your sponsor accompanies you as directed. Learn the short responses with your parish; this guide does not replace the approved ritual.",
"ministerActionsHeading" to "Anointing with Sacred Chrism",
"preparation" to "Confirm the schedule, rehearsal, sponsor arrangements, and any local practice concerning a saint’s name. Afterward, identify a concrete way to serve, continue formation, and share your faith. Confirmation is a beginning for deeper discipleship, not graduation from the Church.",
"preparationHeading" to "Living as a Witness to Christ"), mapOf("title" to "Confirmación",
"meaning" to "La Confirmación fortalece la gracia bautismal y te capacita para dar testimonio de Jesús en la Iglesia y en la vida diaria. Pide al Espíritu Santo valentía, sabiduría y un corazón generoso.",
"meaningHeading" to "Recibir el don del Espíritu Santo",
"context" to "Repasa las promesas bautismales y ora sobre cómo vivirlas. Una persona bautizada debe prepararse para recibir la Confirmación en estado de gracia, recurriendo a la confesión sacramental cuando corresponda. Quien recibe el Bautismo inmediatamente antes no necesita confesarse antes de ese Bautismo. Habla de tu situación en privado con el sacerdote.",
"contextHeading" to "Preparar el corazón y renovar la fe",
"studentActions" to "Confirma la función de tu padrino o madrina y dónde debes colocarte. La parroquia ensayará la presentación de tu nombre, la renovación de las promesas bautismales cuando corresponda y tus respuestas. No necesitas memorizar un discurso; escucha y responde con oración.",
"studentActionsHeading" to "Tu participación y tu padrino o madrina",
"ministerActions" to "El obispo o un sacerdote autorizado ora por el don del Espíritu Santo y unge tu frente con el santo crisma. Tu padrino o madrina te acompaña según las indicaciones. Aprende las respuestas breves con tu parroquia; esta guía no sustituye el ritual aprobado.",
"ministerActionsHeading" to "La unción con el santo crisma",
"preparation" to "Confirma el horario, el ensayo, los preparativos con tu padrino o madrina y cualquier costumbre local sobre el nombre de un santo. Después, elige una manera concreta de servir, continuar tu formación y compartir la fe. La Confirmación inicia un discipulado más profundo; no es una graduación de la Iglesia.",
"preparationHeading" to "Vivir como testigo de Cristo")),
RiteGuideTemplate("sacrament-first-communion", mapOf("title" to "First Holy Communion",
"meaning" to "In Holy Communion you receive Jesus Christ, truly present in the Eucharist. Your first reception belongs within the Church’s celebration of Mass and opens a lifelong pattern of worship, thanksgiving, and communion.",
"meaningHeading" to "Meeting Christ in the Eucharist",
"context" to "Confirm your readiness and the timing of reception with your parish. Those already baptized should discuss first Reconciliation as appropriate; the newly baptized do not need confession between Baptism and first Communion at initiation. Normally fast for one hour before receiving Communion. Ask the parish about the rules and exceptions for illness or other needs; do not alter medication without medical advice.",
"contextHeading" to "Preparing to Receive Communion",
"studentActions" to "Rehearse where to stand and how to receive according to local practice. Listen to the minister’s words and respond Amen. Receive reverently and consume the consecrated host immediately. Tell the parish beforehand about swallowing difficulties, gluten-related conditions, or other needs so appropriate arrangements can be made.",
"studentActionsHeading" to "Approaching and Receiving Reverently",
"ministerActions" to "Participate in the readings, responses, and prayers as well as the Communion procession. The priest leads the Eucharistic Prayer. Your instructor can walk through the order of Mass with you and explain unfamiliar gestures without turning the celebration into a performance.",
"ministerActionsHeading" to "Participating in the Mass",
"preparation" to "After Communion, spend time in quiet thanks to Jesus. Confirm seating and arrival arrangements before the celebration. Continue Sunday Mass and parish life afterward, allowing the gift you receive to shape your prayer, relationships, and service.",
"preparationHeading" to "Thanksgiving and Ongoing Eucharistic Life"), mapOf("title" to "Primera Comunión",
"meaning" to "En la Comunión recibes a Jesucristo, realmente presente en la Eucaristía. Tu primera recepción tiene lugar dentro de la celebración de la Misa e inicia una vida de adoración, acción de gracias y comunión.",
"meaningHeading" to "Encontrarte con Cristo en la Eucaristía",
"context" to "Confirma con la parroquia tu preparación y el momento de recibir. Quienes ya están bautizados deben hablar sobre la primera Reconciliación cuando corresponda; los recién bautizados no necesitan confesarse entre el Bautismo y la primera Comunión en la iniciación. Normalmente se guarda una hora de ayuno antes de comulgar. Pregunta sobre las normas y excepciones por enfermedad u otras necesidades; no cambies tu medicación sin consejo médico.",
"contextHeading" to "Prepararte para comulgar",
"studentActions" to "Ensaya dónde colocarte y cómo recibir según la práctica local. Escucha las palabras del ministro y responde Amén. Recibe con reverencia y consume inmediatamente la hostia consagrada. Informa antes sobre dificultades para tragar, problemas relacionados con el gluten u otras necesidades para organizar los apoyos adecuados.",
"studentActionsHeading" to "Acercarte y recibir con reverencia",
"ministerActions" to "Participa en las lecturas, las respuestas y las oraciones, además de la procesión de Comunión. El sacerdote dirige la Plegaria Eucarística. Tu instructor puede repasar contigo el orden de la Misa y explicar gestos desconocidos sin convertir la celebración en una actuación.",
"ministerActionsHeading" to "Participar en la Misa",
"preparation" to "Después de comulgar, dedica un tiempo a dar gracias a Jesús en silencio. Confirma antes los asientos y la hora de llegada. Continúa participando en la Misa dominical y en la parroquia, dejando que este don transforme tu oración, tus relaciones y tu servicio.",
"preparationHeading" to "Acción de gracias y vida eucarística")),
RiteGuideTemplate("sacrament-first-reconciliation", mapOf("title" to "First Reconciliation",
"meaning" to "Reconciliation is a sacrament of healing for sins committed after Baptism. It is distinct from the three sacraments of initiation. Come trusting in God’s mercy, with sorrow for sin and a sincere intention to change. If you are not yet baptized, speak with your priest about preparation for Baptism instead.",
"meaningHeading" to "Encountering God’s Mercy",
"context" to "Set aside quiet time to pray and review your choices in the light of the Gospel. An examination of conscience can help. Consider how you have harmed your relationship with God or others and where you need to make amends. Keep this reflection private; you are not being asked to submit it to your instructor.",
"contextHeading" to "Examining Your Conscience",
"studentActions" to "Tell the priest this is your first confession and ask for help if you are unsure. Confess your sins honestly; mention remembered grave sins by kind and number as well as you can. Listen to the priest and express contrition. If you forget the words of a prayer, ask him to guide you.",
"studentActionsHeading" to "Making Your First Confession",
"ministerActions" to "The priest listens, may ask clarifying questions, offers counsel, and gives a penance. With the required disposition, you receive absolution through his ministry. Confession is protected by the sacramental seal. This is an encounter with mercy, not an examination of your speaking ability.",
"ministerActionsHeading" to "The Priest’s Guidance and Absolution",
"preparation" to "Complete your penance and thank God. Ask the parish about available times and the option of a screen or face-to-face confession. Never enter sins, confession notes, or what the priest said into this app or a class discussion. The guide’s acknowledgment records only that you read it, not that you confessed.",
"preparationHeading" to "Penance, Thanksgiving, and Privacy"), mapOf("title" to "Primera Reconciliación",
"meaning" to "La Reconciliación es un sacramento de sanación para los pecados cometidos después del Bautismo. Es distinta de los tres sacramentos de iniciación. Acércate confiando en la misericordia de Dios, con dolor por el pecado y el propósito sincero de cambiar. Si aún no estás bautizado, habla con el sacerdote sobre la preparación para el Bautismo.",
"meaningHeading" to "Encontrarte con la misericordia de Dios",
"context" to "Dedica un momento tranquilo a orar y revisar tus decisiones a la luz del Evangelio. Un examen de conciencia puede ayudarte. Considera cómo has dañado tu relación con Dios o con los demás y qué debes reparar. Mantén privada esta reflexión; no se te pide entregarla a tu instructor.",
"contextHeading" to "Examinar tu conciencia",
"studentActions" to "Di al sacerdote que es tu primera confesión y pide ayuda si tienes dudas. Confiesa tus pecados con sinceridad; menciona los pecados graves que recuerdes por su clase y número, según puedas. Escucha al sacerdote y expresa tu contrición. Si olvidas las palabras de una oración, pídele orientación.",
"studentActionsHeading" to "Hacer tu primera confesión",
"ministerActions" to "El sacerdote escucha, puede hacer preguntas para aclarar, ofrece consejo y te da una penitencia. Con la disposición necesaria, recibes la absolución por su ministerio. La confesión está protegida por el sigilo sacramental. Es un encuentro con la misericordia, no una prueba de tu capacidad para hablar.",
"ministerActionsHeading" to "La orientación del sacerdote y la absolución",
"preparation" to "Cumple tu penitencia y da gracias a Dios. Pregunta por los horarios y la posibilidad de confesarte tras una rejilla o cara a cara. Nunca escribas pecados, notas de confesión ni lo que dijo el sacerdote en esta aplicación o en un foro de clase. La confirmación de esta guía registra solo que la leíste, no que te confesaste.",
"preparationHeading" to "Penitencia, acción de gracias y privacidad"))
 )
}
