package com.illumined.app.ui

import java.util.Locale

/** Translates known app-generated errors while leaving Firebase and user content intact. */
internal fun localizedUserMessage(message: String): String {
    if (Locale.getDefault().language != "es") return message
    return spanishUserMessages[message] ?: message
}

private val spanishUserMessages = mapOf(
    "Something went wrong. Please try again." to "Algo salió mal. Inténtalo de nuevo.",
    "Enter a valid email address." to "Ingresa una dirección de correo electrónico válida.",
    "The email or password was not correct." to "El correo electrónico o la contraseña no eran correctos.",
    "That email already has an account. Try signing in instead." to "Ese correo electrónico ya tiene una cuenta. Intenta iniciar sesión.",
    "Use a password with at least 6 characters." to "Usa una contraseña de al menos 6 caracteres.",
    "Too many attempts. Please wait a few minutes and try again." to "Demasiados intentos. Espera unos minutos e inténtalo de nuevo.",
    "Enter your email address first, then request a password reset." to "Ingresa primero tu correo electrónico y luego solicita restablecer la contraseña.",
    "Password reset email sent. Check your inbox for a secure reset link." to "Se envió el correo para restablecer la contraseña. Revisa tu bandeja de entrada.",
    "Please sign in before editing." to "Inicia sesión antes de editar.",
    "You can only edit your own response." to "Solo puedes editar tu propia respuesta.",
    "Please write a response before saving." to "Escribe una respuesta antes de guardarla.",
    "Please sign in before deleting." to "Inicia sesión antes de eliminar.",
    "You can only delete your own response." to "Solo puedes eliminar tu propia respuesta.",
    "Please sign in before posting." to "Inicia sesión antes de publicar.",
    "Please join a class before posting." to "Únete a una clase antes de publicar.",
    "Please write a response before posting." to "Escribe una respuesta antes de publicarla.",
    "You already posted a response for this discussion. Edit or delete your original response to post a new one." to
        "Ya publicaste una respuesta en este debate. Edita o elimina tu respuesta original para publicar una nueva.",
    "Please sign in before replying." to "Inicia sesión antes de responder.",
    "Please join a class before replying." to "Únete a una clase antes de responder.",
    "Please write a reply before posting." to "Escribe una respuesta antes de publicarla.",
    "Please sign in before sending messages." to "Inicia sesión antes de enviar mensajes.",
    "Please join a class before sending messages." to "Únete a una clase antes de enviar mensajes.",
    "That instructor invite code was not found." to "No se encontró ese código de invitación para instructores.",
    "That instructor invite code has already been used." to "Ese código de invitación para instructores ya fue utilizado.",
    "Please sign in before creating another class." to "Inicia sesión antes de crear otra clase.",
    "Enter a class ID." to "Ingresa un ID de clase.",
    "Class IDs must be 100 characters or fewer and cannot contain a slash." to "Los ID de clase deben tener 100 caracteres o menos y no pueden contener una barra diagonal.",
    "Instructor access is required." to "Se requiere acceso de instructor.",
    "That class ID is already attached to your account." to "Ese ID de clase ya está asociado a tu cuenta.",
    "That class ID could not be created. It may already be in use." to "No se pudo crear ese ID de clase. Es posible que ya esté en uso.",
    "That parish setup code was not found." to "No se encontró ese código de configuración parroquial.",
    "That parish setup code has already been used." to "Ese código de configuración parroquial ya fue utilizado.",
    "Please sign in before starting a new class." to "Inicia sesión antes de crear una clase nueva.",
    "Please sign in before saving a profile." to "Inicia sesión antes de guardar un perfil.",
    "Please enter both your name and class ID." to "Ingresa tu nombre y el ID de la clase.",
    "Please enter your name, parish name, class ID, and setup code." to "Ingresa tu nombre, el nombre de la parroquia, el ID de la clase y el código de configuración.",
    "Please sign in before switching classes." to "Inicia sesión antes de cambiar de clase.",
    "You can only switch to a class assigned to your instructor profile." to
        "Solo puedes cambiar a una clase asignada a tu perfil de instructor.",
    "Please sign in before updating an assignment." to "Inicia sesión antes de actualizar una tarea.",
    "Please join a class before updating assignments." to "Únete a una clase antes de actualizar las tareas.",
    "Please sign in before updating lesson progress." to "Inicia sesión antes de actualizar el progreso de la lección.",
    "Please sign in before updating prayer progress." to "Inicia sesión antes de actualizar el progreso de oración.",
    "Please sign in before updating Selected Prayers." to "Inicia sesión antes de actualizar las oraciones seleccionadas.",
    "Please sign in before acknowledging a prayer request." to "Inicia sesión antes de responder a una petición de oración.",
    "Your classmates can acknowledge your prayer request." to "Tus compañeros pueden responder a tu petición de oración.",
    "Please choose a valid prayer response." to "Elige una respuesta de oración válida.",
    "Please sign in before updating Rosary progress." to "Inicia sesión antes de actualizar el progreso del Rosario.",
    "Please sign in before posting a prayer request." to "Inicia sesión antes de publicar una petición de oración.",
    "Please add a title for the prayer request." to "Añade un título para la petición de oración.",
    "Please join a class before posting a prayer request." to "Únete a una clase antes de publicar una petición de oración.",
    "Please sign in before deleting your account." to "Inicia sesión antes de eliminar tu cuenta.",
    "This account does not have an email address." to "Esta cuenta no tiene una dirección de correo electrónico.",
    "Enter your password to continue." to "Ingresa tu contraseña para continuar.",
    "The password was not correct. Your account was not deleted." to "La contraseña no era correcta. Tu cuenta no fue eliminada.",
    "Please sign in again, then return here to delete your account." to "Vuelve a iniciar sesión y regresa aquí para eliminar tu cuenta.",
    "Account deletion is temporarily unavailable. Please try again." to "La eliminación de la cuenta no está disponible temporalmente. Inténtalo de nuevo.",
    "Your account could not be deleted. Nothing has been changed. Please try again." to
        "No se pudo eliminar tu cuenta. No se cambió nada. Inténtalo de nuevo.",
    "Classroom lessons could not be loaded." to "No se pudieron cargar las lecciones de la clase.",
    "Please sign in before registering notifications." to "Inicia sesión antes de registrar las notificaciones.",
    "A valid notification token is required." to "Se requiere un token de notificación válido.",
    "Please sign in before creating invite codes." to "Inicia sesión antes de crear códigos de invitación.",
    "Only instructors can create invite codes." to "Solo los instructores pueden crear códigos de invitación.",
    "Assign your instructor profile to a class before creating invite codes." to "Asigna tu perfil de instructor a una clase antes de crear códigos de invitación.",
    "Please sign in before creating parish setup codes." to "Inicia sesión antes de crear códigos de configuración parroquial.",
    "Only app admins can create parish setup codes." to "Solo los administradores de la aplicación pueden crear códigos de configuración parroquial.",
    "Please assign your instructor profile to a class first." to "Primero asigna tu perfil de instructor a una clase.",
    "Please add both a title and message." to "Añade un título y un mensaje.",
    "Please add a class topic." to "Añade un tema para la clase.",
    "Please add an assignment title." to "Añade un título para la tarea.",
    "Please add a title and prompt." to "Añade un título y una consigna.",
    "Please add both a title and full text for each reading." to "Añade un título y el texto completo de cada lectura.",
    "Use a reminder time in HH:mm format." to "Usa una hora de recordatorio con el formato HH:mm.",
    "Enter a valid time zone, such as America/New_York." to "Ingresa una zona horaria válida, como America/New_York.",
    "Choose a valid calendar date." to "Elige una fecha válida del calendario.",
    "Add both a title and details." to "Añade un título y los detalles.",
    "Choose a valid Daily Formation type." to "Elige un tipo válido de Formación diaria.",
    "Choose a valid liturgical color." to "Elige un color litúrgico válido.",
    "There are no valid Daily Formation entries to import." to "No hay entradas válidas de Formación diaria para importar.",
    "There are no class dates to import." to "No hay fechas de clase para importar.",
    "Please sign in before editing Daily Formation." to "Inicia sesión antes de editar la Formación diaria.",
    "Please sign in before deleting Daily Formation." to "Inicia sesión antes de eliminar una entrada de Formación diaria.",
    "Please sign in before importing Daily Formation." to "Inicia sesión antes de importar la Formación diaria.",
    "Only instructors can edit Daily Formation." to "Solo los instructores pueden editar la Formación diaria.",
    "Only instructors can import Daily Formation." to "Solo los instructores pueden importar la Formación diaria.",
    "Please sign in before creating an announcement." to "Inicia sesión antes de crear un anuncio.",
    "Please sign in before editing an announcement." to "Inicia sesión antes de editar un anuncio.",
    "Please sign in before deleting an announcement." to "Inicia sesión antes de eliminar un anuncio.",
    "Only instructors can create announcements." to "Solo los instructores pueden crear anuncios.",
    "Only instructors can edit announcements." to "Solo los instructores pueden editar anuncios.",
    "Only instructors can delete announcements." to "Solo los instructores pueden eliminar anuncios.",
    "Please sign in before creating a class schedule item." to "Inicia sesión antes de crear una fecha en el calendario de clases.",
    "Please sign in before editing a class schedule item." to "Inicia sesión antes de editar una fecha del calendario de clases.",
    "Please sign in before deleting a class schedule item." to "Inicia sesión antes de eliminar una fecha del calendario de clases.",
    "Please sign in before importing the class schedule." to "Inicia sesión antes de importar el calendario de clases.",
    "Only instructors can edit the class schedule." to "Solo los instructores pueden editar el calendario de clases.",
    "Only instructors can import the class schedule." to "Solo los instructores pueden importar el calendario de clases.",
    "Please sign in before creating an assignment." to "Inicia sesión antes de crear una tarea.",
    "Please sign in before editing an assignment." to "Inicia sesión antes de editar una tarea.",
    "Please sign in before deleting an assignment." to "Inicia sesión antes de eliminar una tarea.",
    "Only instructors can create assignments." to "Solo los instructores pueden crear tareas.",
    "Only instructors can edit assignments." to "Solo los instructores pueden editar tareas.",
    "Only instructors can delete assignments." to "Solo los instructores pueden eliminar tareas.",
    "Please sign in before creating a discussion." to "Inicia sesión antes de crear un debate.",
    "Please sign in before editing a discussion prompt." to "Inicia sesión antes de editar una consigna de debate.",
    "Please sign in before deleting a discussion prompt." to "Inicia sesión antes de eliminar una consigna de debate.",
    "Only instructors can create discussion prompts." to "Solo los instructores pueden crear consignas de debate.",
    "Only instructors can edit discussion prompts." to "Solo los instructores pueden editar consignas de debate.",
    "Only instructors can delete discussion prompts." to "Solo los instructores pueden eliminar consignas de debate.",
)
