import {test} from 'node:test';
import assert from 'node:assert/strict';
import {initializeApp} from 'firebase-admin/app';
import {getFirestore,Timestamp} from 'firebase-admin/firestore';
import {classroomRefreshments,deliverRefreshmentReminders} from './refreshments.js';
const enabled=process.env.FIRESTORE_EMULATOR_HOST==='127.0.0.1:8199';
if(enabled)initializeApp({projectId:'demo-refreshments'});
test('sheet permissions, competing claims, instructor reassignment, stale edits, and isolated reminders',{skip:!enabled},async()=>{
 const db=getFirestore();
 // Only the hard-gated demo-refreshments emulator project is reset.
 for(const collection of await db.listCollections()) await db.recursiveDelete(collection);
 for(const [id,classes,teacher] of [['a',['room'],false],['b',['room'],false],['teacher',['room'],true],['outsider',['other'],true]])
   await db.doc('userProfiles/'+id).set({classIds:classes,isInstructor:teacher,displayName:id,fcmTokens:['token-'+id],notificationsEnabled:true});
 await db.doc('classrooms/room').set({isArchived:false});
 await db.doc('classrooms/room/settings/dailyFormation').set({timeZone:'America/New_York'});
 for(const id of ['one','two'])await db.doc('classSchedule/'+id).set({classId:'room',date:Timestamp.fromDate(new Date('2099-10-04T15:00:00Z')),topic:id});
 const call=(uid,data={})=>classroomRefreshments.run({auth:uid?{uid}:undefined,data:{classId:'room',...data}});
 for(const uid of [null,'outsider'])await assert.rejects(()=>call(uid));
 for(const uid of ['a','outsider'])await assert.rejects(()=>call(uid,{action:'configure',enabled:false}));
 await assert.rejects(()=>call('teacher',{action:'configure',enabled:'false'}));
 const sheet=await call('a');assert.equal(sheet.days.length,1);assert.deepEqual(sheet.students,[]);
 const day=sheet.days[0].day;
 const race=await Promise.allSettled(['a','b'].map(uid=>call(uid,{action:'save',day,volunteerId:uid,revision:0,notes:'Fruit'})));
 assert.equal(race.filter(x=>x.status==='fulfilled').length,1);
 const winner=(await call('a')).days[0].volunteerId,other=winner==='a'?'b':'a';
 await assert.rejects(()=>call(other,{action:'save',day,volunteerId:other,revision:1}));
 await assert.rejects(()=>call(other,{action:'cancel',day,revision:1}));
 await call(winner,{action:'save',day,volunteerId:winner,revision:1,notes:'Water'});
 await assert.rejects(()=>call(winner,{action:'cancel',day,revision:1}));
 await call('teacher',{action:'save',day,volunteerId:other,revision:2,notes:'Reassigned'});
 assert.equal((await call('a')).days[0].volunteerId,other);
 const sends=[],send=async data=>{sends.push(data);return {successCount:1};};
 const now=new Date('2099-10-03T14:00:00Z');
 await call('teacher',{action:'configure',enabled:false});
 const disabled=await call('a');assert.equal(disabled.enabled,false);assert.deepEqual(disabled.days,[]);
 await assert.rejects(()=>call(other,{action:'save',day,volunteerId:other,revision:3}));
 await assert.rejects(()=>call('teacher',{action:'cancel',day,revision:3}));
 await deliverRefreshmentReminders(db,send,now);assert.equal(sends.length,0);
 await call('teacher',{action:'configure',enabled:true});
 assert.equal((await call('a')).days[0].volunteerId,other);
 assert.equal((await call('a')).days[0].notes,'Reassigned');
 await Promise.all([deliverRefreshmentReminders(db,send,now),deliverRefreshmentReminders(db,send,now)]);
 assert.equal(sends.length,1);assert.deepEqual(sends[0].tokens,['token-'+other]);assert.equal(sends[0].data.recipientId,other);
 await call(other,{action:'cancel',day,revision:3});
 await deliverRefreshmentReminders(db,send,now);assert.equal(sends.length,1);
 await db.doc('userProfiles/a').update({inactiveClassIds:['room']});await assert.rejects(()=>call('a'));
 await assert.rejects(()=>call('teacher',{action:'save',day,volunteerId:'a',revision:4}));
 await db.doc('classSchedule/one').delete();await db.doc('classSchedule/two').delete();
 await assert.rejects(()=>call('teacher',{action:'save',day,volunteerId:'b',revision:4}));
 assert.equal((await call('teacher')).days.length,0);
 await db.doc('classrooms/room').update({isArchived:true});await assert.rejects(()=>call('teacher'));
});
test('reminders skip muted/removed volunteers, cancelled dates and archived classrooms',{skip:!enabled},async()=>{
 const db=getFirestore(),room='reminder-safety',uid='muted-volunteer';
 const classRef=db.doc('classrooms/'+room),person=db.doc('userProfiles/'+uid),schedule=db.doc('classSchedule/safety');
 await classRef.set({isArchived:false});await classRef.collection('settings').doc('dailyFormation').set({timeZone:'America/New_York'});
 await person.set({classIds:[room],notificationsEnabled:false,fcmTokens:['safety-token']});
 const session={classId:room,date:Timestamp.fromDate(new Date('2099-10-04T15:00:00Z')),topic:'Safety'};
 await schedule.set(session);
 await db.doc('refreshmentSignups/'+room+'__2099-10-04').set({classId:room,day:'2099-10-04',volunteerId:uid,revision:1});
 const sent=[],send=async message=>{sent.push(message);return {successCount:1};},now=new Date('2099-10-03T14:00:00Z');
 await deliverRefreshmentReminders(db,send,now);assert.equal(sent.length,0);
 await person.update({notificationsEnabled:true,removedClassIds:[room]});await deliverRefreshmentReminders(db,send,now);assert.equal(sent.length,0);
 await person.update({removedClassIds:[]});await classRef.update({isArchived:true});await deliverRefreshmentReminders(db,send,now);assert.equal(sent.length,0);
 await classRef.update({isArchived:false});await schedule.delete();await deliverRefreshmentReminders(db,send,now);assert.equal(sent.length,0);
 await schedule.set(session);await deliverRefreshmentReminders(db,send,now);assert.equal(sent.length,1);
});
test('manual volunteers reserve the slot, are instructor-only, and receive no account push',{skip:!enabled},async()=>{
 const db=getFirestore(),classId='manual-room',day='2099-10-04';
 await db.doc('classrooms/'+classId).set({isArchived:false});
 await db.doc('classSchedule/manual').set({classId,date:Timestamp.fromDate(new Date(day+'T15:00:00Z')),topic:'Manual volunteer'});
 for(const [uid,teacher] of [['manual-teacher',true],['manual-student',false]])await db.doc('userProfiles/'+uid).set({classIds:[classId],isInstructor:teacher,displayName:uid,fcmTokens:['token-'+uid]});
 const call=(uid,data)=>classroomRefreshments.run({auth:{uid},data:{classId,day,...data}});
 for(const manualName of ['', '   ', 'x'.repeat(121)])await assert.rejects(()=>call('manual-teacher',{action:'save',manualName,revision:0}));
 await assert.rejects(()=>call('manual-student',{action:'save',manualName:'Guest',revision:0}));
 await assert.rejects(()=>call('outsider',{action:'save',manualName:'Guest',revision:0}));
 await assert.rejects(()=>call('manual-teacher',{action:'save',volunteerId:'manual-student',manualName:'Spoof',revision:0}));
 await call('manual-teacher',{action:'save',manualName:'  Jane Doe  ',notes:'Cookies',revision:0});
 let row=(await call('manual-student',{action:'list'})).days[0];assert.equal(row.volunteerName,'Jane Doe');assert.equal(row.volunteerId,'');assert.equal(row.notes,'Cookies');
 await assert.rejects(()=>call('manual-student',{action:'save',volunteerId:'manual-student',revision:1}));
 await assert.rejects(()=>call('manual-student',{action:'cancel',revision:1}));
 const sent=[];await deliverRefreshmentReminders(db,async message=>{sent.push(message);return {successCount:1};},new Date('2099-10-03T14:00:00Z'));
 assert.equal(sent.filter(message=>message.data.classId===classId).length,0);
 await call('manual-teacher',{action:'save',manualName:'Janet Doe',revision:1});
 await call('manual-teacher',{action:'save',volunteerId:'manual-student',revision:2});
 row=(await call('manual-student',{action:'list'})).days[0];assert.equal(row.volunteerId,'manual-student');assert.equal(row.volunteerName,'manual-student');
 await call('manual-teacher',{action:'save',manualName:'Guest again',revision:3});
 await call('manual-teacher',{action:'cancel',revision:4});
 await call('manual-student',{action:'save',volunteerId:'manual-student',revision:5});
});
